[profile.default]
solc_version="0.8.27"
src = "contracts"
out = "out"
fs_permissions = [{ access = "read-write", path = "./out"}]
libs = ["lib"]
optimizer = true
optimizer_runs = 200
via_ir = true
retries = 2
