[profile.default]
solc_version="0.8.27"
src = "contracts"
out = "out"
fs_permissions = [{ access = "read-write", path = "./out"}]
libs = ["lib"]
optimizer = true
optimizer_runs = 1000000
via_ir = true
retries = 2
evm_version = "paris"
cbor_metadata = false
bytecode_hash = "none"
